project_id = "uoqierhqpnqnbsnbzaqa"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[edge_functions]
enabled = true
port = 54327

[functions.create-checkout]
verify_jwt = false

[functions.paytech-webhook]
verify_jwt = false

[functions.test-paytech-connection]
verify_jwt = false

[functions.check-expired-subscriptions]
verify_jwt = false